### ISSUE TITLE
pio0 used by software serial?

### ISSUE THREAD

**Issue by eried** [MrYsLab/NeoPixelConnect#6]
Hi, im trying to quickly understand why opening a softwareserial makes this stop working, is there is an easy way to not use any pio? i.e. just bitbang in the "main" thread?

**Comment by MrYsLab** [comment]
Hi Erwin,
Thanks for the question. Bitbanging control of NeoPixels is highly complex in that the timing must be exact down to the microsecond level. [Here is an article ](https://www.instructables.com/Bitbanging-step-by-step-Arduino-control-of-WS2811-/)that describes the process for an Uno R3. It is also very processor-intense and may only allow little more than driving the NeoPixels to occur.

The NeoPixelConnect library allows one to select either pio0 or pio1 and to select a state matching to use in the PIO. [Here is a pointer](https://github.com/MrYsLab/NeoPixelConnect/blob/826298390bbed50d6c83c10c1bca0cf00d2a4efb/src/NeoPixelConnect.h#L56) to the constructor that allows you to specify this. Both of the [examples provided](https://github.com/MrYsLab/NeoPixelConnect/tree/master/examples) use this constructor.

Please let me know if this answers your question, and if it does, please close the issue. Also, feel free to ask any other questions you may have.

**Comment by eried** [comment]
Hey thanks for the article, I will check it out
