### ISSUE TITLE
#define MAXIMUM_NUM_NEOPIXELS is misplaced in the example.

### ISSUE THREAD

**Issue by vfr1200f** [MrYsLab/NeoPixelConnect#7]
`#define MAXIMUM_NUM_NEOPIXELS 8 `
should be before 
`#include <NeoPixelConnect.h>`
in the example.
I get redefinition error otherwise. Placing it before the include actually works.

**Comment by MrYsLab** [comment]
Thanks for reporting this. It is fixed in release 1.2.1
